services:
  discovery-service:
    build: ./
    container_name: discovery-service
    healthcheck:
      test: [ "CMD", 'sh', '-c', 'echo -e "Checking service availability"; while ! nc -z "discovery-service" 4080; do sleep 1; printf "-"; done; echo -e " >> Service has started";' ]
      timeout: 10s
      retries: 10
    ports:
      - "4080:4080"
    expose:
      - "4080"
    networks:
      - fcNet
      - jaegerNet
    env_file:
      - ./.env
    environment:
      - OTEL_SERVICE_NAME=discovery-service
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL}
      - TZ=${TIMEZONE}

networks:
  fcNet:
    name: fcNet
    driver: bridge
  jaegerNet:
    name: jaegerNet
    external: true
    driver: bridge