services:
  discovery-service:
    build: ./
    container_name: discovery-service
    healthcheck:
      test: [ "CMD", 'sh', '-c', 'echo -e "Checking service availability"; while ! nc -z "discovery-service" 4080; do sleep 1; printf "-"; done; echo -e " >> Service has started";' ]
      timeout: 10s
      retries: 10
    ports:
      - "4080:4080"
    expose:
      - "4080"
    networks:
      - fcNet
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - OTEL_TRACES_EXPORTER=logging
      - OTEL_METRICS_EXPORTER=logging
      - OTEL_LOGS_EXPORTER=logging
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - TZ=Africa/Lagos

networks:
  fcNet:
    name: fcNet
    driver: bridge