services:
  redis:
    image: redis:7.2
    container_name: fc-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
#      - "6380:6379"
#    network_mode: host
    networks:
      - fcNet
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: fc-zipkin
    restart: always
    ports:
      - "9411:9411"
    expose:
      - "9411"
    networks:
      - fcNet
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  collector:
    container_name: fc-collector
    image: otel/opentelemetry-collector-contrib:0.91.0
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    restart: always
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "8889:8889" # Prometheus exporter metrics
    networks:
      - fcNet
    depends_on:
      - loki
      - jaeger
      - zipkin
      - tempo

  tempo:
    container_name: fc-tempo
    image: grafana/tempo:2.3.1  # or 1.5.0
    #    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml
    restart: always
    ports:
      - "4317"  # otlp grpc
      - "3200"  # tempo as grafana datasource
    networks:
      - fcNet


  loki:
    container_name: fc-loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    ports:
      - "3100"
    networks:
      - fcNet


  prometheus:
    container_name: fc-prometheus
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
    restart: always
    ports:
      - '9090:9090'
    networks:
      - fcNet

    depends_on:
      - collector

  grafana:
    container_name: fc-grafana
    image: grafana/grafana
    volumes:
      - ./docker/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: always
    ports:
      - "3001:3000"
    networks:
      - fcNet

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
      - loki
      - jaeger
      - zipkin
      - tempo

  jaeger:
    container_name: fc-jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always
    ports:
      - "16686:16686"
      - "4317"
    networks:
      - fcNet


  fc-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fc-rabbitmq
    networks:
      - fcNet

    ports:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./.volumes/rabbitmq:/var/lib/rabbitmq/mnesia
    restart: always

volumes:
  redis_data:
  artemis-data:

networks:
  fcNet:
    name: fcNet
    driver: bridge